sudo: required

services:
  - docker

before_install:
  - docker build -t ahammoudeh/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ahammoudeh/docker-react npm run test
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-973273474155"
    bucket: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_access_key
    secret_access_key:
      secure: "$AWS_secret_key"
