sudo: required

services:
  - docker

before_install:
  - docker build -t ahammoudeh/docker-react -f Dockerfile.dev .
scripts:
  - docker run -e CI=true ahammoudeh/docker-react npm run test -- --coverage